### ISSUE TITLE
Deploy using API (spotinst-sdk-java)

### ISSUE THREAD

**Issue by LeandroMichelson** [spotinst/spotinst-sdk-java#38]
Boa noite, não sei o que aconteceu, mas na versão 1.0.15 “spotinst-sdk-java” tinha os métodos “ElastigroupDeployInstancesRequest” e “SpotinstElastigroupClient.deployInstances”, onde você poderia fazer deploy, da versão 1.0.16 em diante, foi removido por engano? Ou agora existe uma nova maneira de fazer isso?
Outra observação é que o "Strategy" que estava na versão 1.0.15, não tem o mesmo "onFailure" que está na documentação (Deploy - Spotinst API), pois queria usá-lo para poder fazer "DETACH_NEW".

Voltará em novas versões? Ou isso pode ser feito no atual? Gostaria de um exemplo, se possível (usando a API).

Good night, I don't know what happened, but in version 1.0.15 “spotinst-sdk-java” had the methods “ElastigroupDeployInstancesRequest” and “SpotinstElastigroupClient.deployInstances”, where you could deploy them, from version 1.0.16 on onwards, was it removed by mistake? Or is there now a new way to do this?
Another observation is that the "Strategy" that was in version 1.0.15, does not have the same "onFailure" that is in the documentation (Deploy - Spotinst API), because I wanted to use it to be able to do "DETACH_NEW".

Will it come back in new versions? Or can this be done in the current one? I would like an example, if possible (using the API).

![ElastigroupDeployInstancesRequest](https://user-images.githubusercontent.com/31194361/105096311-9ca2d780-5a85-11eb-994f-e2fead9ad73d.png)
![SpotinstElastigroupClient-DeployInstances](https://user-images.githubusercontent.com/31194361/105096312-9dd40480-5a85-11eb-9493-83432eb57528.png)

**Comment by anuragsharma-123** [comment]
Hi,

Is it still an open issue. I checked in the latest SDK, both above observations seems to be resolved. Please let me know so that I can close the ticket.

Anurag

**Comment by anuragsharma-123** [comment]
No response from the reporter on this ticket. Closing.
